const {run,row,R,OUT,seedV1,dAgo,fs}=require('./personas');
(async()=>{
await run('tanaka',seedV1('beginner'),async P=>{const p=P.page;
  await P.shot('ホーム');
  await P.tap(p.getByText('今日の記録をつける'),'今日の記録をつける');await P.shot('種目を選ぶ');
  await P.tap(row(p,/^ベンチプレス/),'ベンチプレス');
  await P.tap('[data-a="w+"][data-i="0"]','重さ＋');await P.tap('[data-a="w+"][data-i="0"]','重さ＋');
  await P.tap('[data-c="0"]','✓1');await P.tap('[data-c="1"]','✓2');await P.tap('[data-c="2"]','✓3');await P.shot('自己ベストとタイマー');
  await P.tap(p.getByText('次の種目へ'),'次の種目へ');
  await P.tap(row(p,/^ラットプルダウン/),'ラットプルダウン');await P.type('[data-f="w"][data-i="0"]',35,'重さ');await P.type('[data-f="r"][data-i="0"]',10,'回数');
  await P.tap('#as','セットを足す');await P.tap('#as','セットを足す');await P.shot('はじめての種目');
  await P.tap(p.getByText('保存して戻る'),'保存して戻る');await P.shot('今日の記録');
  await P.tap(p.locator('nav button',{hasText:'ホーム'}),'ホーム');await P.shot('ホーム_記録後');
});
await run('sato',null,async P=>{const p=P.page;
  await P.tap(p.getByText('今日の記録をつける'),'今日の記録をつける');
  await P.tap(row(p,/^腕立て伏せ/),'腕立て伏せ');
  await P.type('[data-f="r"][data-i="0"]',15,'回数だけ');await P.tap('#as','セットを足す');await P.tap('#as','セットを足す');await P.shot('自重');
  await P.tap(p.getByText('次の種目へ'),'次の種目へ');
  await P.type('#q','プランク','検索');await P.tap(p.getByText('新しい種目として足す'),'新しい種目として足す');
  await P.page.locator('#pt').selectOption('腹');P.note('部位: 腹');await P.page.locator('#cu').selectOption('秒');P.note('数え方: 秒');await P.shot('新しい種目');
  await P.tap(p.getByText('登録してこの種目を記録'),'登録');await P.type('[data-f="r"][data-i="0"]',30,'秒');await P.tap('#as','セットを足す');await P.shot('秒の種目');
  await P.tap(p.getByText('保存して戻る'),'保存して戻る');await P.shot('今日の記録');
  await P.tap(p.locator('nav button',{hasText:'ふり返り'}),'ふり返り');await P.shot('カレンダー');
});
await run('yamamoto',seedV1('bench'),async P=>{const p=P.page;
  await P.tap(p.getByText('今日の記録をつける'),'今日の記録をつける');
  await P.tap(row(p,/^ベンチプレス/),'ベンチプレス');await P.shot('前回の重さが入っとる');
  await P.type('[data-f="w"][data-i="1"]',92.5,'2セット目の重さ');
  await P.tap('[data-c="0"]','✓1');await P.tap('[data-c="1"]','✓2');await P.page.waitForTimeout(1300);await P.shot('自己ベストと休憩タイマー');
  await P.tap('[data-c="2"]','✓3');await P.tap('[data-a="r-"][data-i="3"]','4セット目 回数−');await P.tap('[data-c="3"]','✓4');
  await P.tap('#hx','ベンチのこれまでの記録');await P.shot('種目の記録一覧');
  await P.tap('#hl','戻る');await P.tap(p.getByText('保存して戻る'),'保存して戻る');
  await P.tap(p.locator('nav button',{hasText:'ふり返り'}),'ふり返り');await P.tap(p.locator('.seg button',{hasText:'グラフ'}),'グラフ');
  await P.tap(p.locator('.chips button',{hasText:'胸'}),'胸');await P.shot('グラフ_胸');
});
await run('suzuki',seedV1('commuter'),async P=>{const p=P.page;
  await P.shot('ホーム');
  await P.tap(p.locator('.cal td[data-d="'+dAgo(1)+'"]'),'昨日の日付');await P.shot('昨日');
  await P.tap('#addx','＋ 種目を足す');await P.tap(row(p,/^ベンチプレス/),'ベンチプレス');await P.shot('片手で保存');
  await P.tap(p.getByText('次の種目へ'),'次の種目へ(前回と同じ)');
  await P.tap(row(p,/^ダンベルショルダープレス/),'ショルダー');await P.tap(p.getByText('保存して戻る'),'保存して戻る');await P.shot('昨日の記録');
});
await run('takahashi',seedV1('analyst'),async P=>{const p=P.page;
  await P.shot('ホーム_控えのお知らせ');
  await P.tap(p.locator('nav button',{hasText:'ふり返り'}),'ふり返り');
  await P.tap(p.locator('.seg button',{hasText:'グラフ'}),'グラフ');await P.shot('週ごとの総重量');
  await P.tap(p.locator('.gbox[data-ex="e0"]'),'ベンチプレスのグラフを押す');await P.shot('種目の記録一覧');
  await P.tap(p.locator('nav button',{hasText:'体重'}),'体重');await P.shot('体重');
  await P.tap(p.locator('nav button',{hasText:'設定'}),'設定');await P.shot('設定');
});
fs.writeFileSync(OUT+'/log.md',R.join('\n\n'));console.log(R.join('\n\n'));
})();
